<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>boo</string>
	</array>
	<key>name</key>
	<string>Boo</string>
	<key>scopeName</key>
	<string>source.boo</string>
	<key>uuid</key>
	<string>1eedcd80-8a64-11e2-9e96-0800200c9a66</string>
</dict>
</plist>
